<?php

namespace AppBundle\Repository;

/**
 * customerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customerRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneByIdJoinedToEmail_addresses($productId)
    {
        $query = $this->getEntityManager($productId)
            ->createQuery(
                'SELECT p, c 
        FROM AppBundle:customer p
        JOIN p.email_addresses c
        WHERE p.active = 1'
            );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }





}
