<?php

namespace AppBundle\Repository;

/**
 * email_addressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class email_addressesRepository extends \Doctrine\ORM\EntityRepository
{
}
